name: new_feature
description: "A new feature package."
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0